version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15672:15672
      - 5672:5672
    
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
    
  admin-mongo:
    image: 0x59/admin-mongo:latest
    ports:
        - 8082:8082
    environment:
        - PORT=8082
        - CONN_NAME=mongo
        - DB_HOST=mongo